name: "cbva-web"

services:
  app:
    build: .
    ports:
      - "5174:5174"
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:54321/cbva
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: cbva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*

  e2e_postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: e2e
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*

volumes:
  postgres_data:
  e2e_postgres_data:
